---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - obs-studio
        - gnome-tweaks
        - wallch
        - grub-customizer
        - steam

  - name: install snap
    command: snap install brave
   

  


