---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - obs-studio
        - gnome-tweaks
        - wallch
        - grub-customizer
        - steam

  tasks:
  - name: Snaps
    community.general.snap:
      name: brave
   

  


